apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvat-frontend
  namespace: cvat
  labels:
    app: cvat-app
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cvat-app
      tier: frontend
  template:
    metadata:
      labels:
        app: cvat-app
        tier: frontend
    spec:
      containers:
        - name: cvat-frontend-app-container
          image: {{IMAGE_TAG}}
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cvat-frontend-service
  namespace: cvat
  labels:
    app: cvat-app
    tier: frontend
spec:
  type: ClusterIP
  selector:
      app: cvat-app
      tier: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
