apiVersion: v1
kind: Service
metadata:
  name: cvat-opa-service
  namespace: cvat
  labels:
    app: cvat-app
    tier: opa-app
spec:
  type: ClusterIP
  selector:
      app: cvat-app
      tier: opa-app
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: http
